
services:
  pg-db:
    container_name: postgres_db
    image: postgres:latest
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: spring-db1
    networks:
      - pow-nw
    ports:
      - 5432:5432

  apache-kafka:
    image: apache/kafka:3.9.0
    container_name: kafka
    ports:
      - 9092:9092
    networks:
      - pow-nw
networks:
  pow-nw:

# postgres://postgres:postgres|