spring.application.name: web

spring:
  profiles:
    active:
    - git
    - config-server
    - email
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-db1
    username: postgres
    password: postgres
  sql:
    init:
      mode: never