###  Add a product
POST {{baseUrl}}/products/v1 HTTP/1.1
Content-Type: application/json

{
    "code": "P3",
    "description": "Product 3"
}
### Fetch all products
GET {{baseUrl}}/products/v1 HTTP/1.1
Content-Type: application/json


### Fetch a product
GET {{baseUrl}}/products/v1/P3 HTTP/1.1
Content-Type: application/json

###
PUT {{baseUrl}}/products/v1/P3 HTTP/1.1
Content-Type: application/json

{
    "description":"Product 3 updated"
}
### invaild product
PUT {{baseUrl}}/products/v1/PX HTTP/1.1
Content-Type: application/json

{
    "description":"Product 2 updated"
}
###
DELETE {{baseUrl}}/products/v1/P2 HTTP/1.1
Content-Type: application/json