spring:
  datasource:
    url: jdbc:postgresql://pg-db:5432/spring-db1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true